const MODELS = {
  SHORT_ANSWER: 'SHORT_ANSWER',
  PARAGRAPH: 'PARAGRAPH',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  CHECKBOXES: 'CHECKBOXES',
  DROPDOWN: 'DROPDOWN',
  DATE: 'DATE',
  TIME: 'TIME',
};

const QUESTION_TYPE = {
  TITLE_AND_DESCRIPTION: 'TITLE_AND_DESCRIPTION',
  QUESTION: 'QUESTION',
};

module.exports = {
  MODELS,
  QUESTION_TYPE,
};
